# Work in progress coming soon...
spring:
  data:
    mongodb:
      host: 10.244.0.3
      port: 27017
      database: desert21
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}


