application:
  jwt:
    secretKey: ${SECRET_KEY}
    prefix: 'Bearer '
    tokenExpirationAfterDays: 14

general:
  ai-player:
    id: "desert-21-ai"
    name: "Desert 21 AI"

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: desert21

  main:
    allow-circular-references: true

  authentication:
    email:
      name: "Desert 21"
      address: registration@email.desert21.com
      token: ${EMAIL_TOKEN}
    cors:
      origins:
        - http://localhost:4200

  addresses:
    baseUrl: http://localhost:4200

server:
  servlet:
    context-path: /api