application:
  jwt:
    secretKey: ${SECRET_KEY}
    prefix: 'Bearer '
    tokenExpirationAfterDays: 14

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: desert21
  main:
    allow-circular-references: true
  authentication:
    email:
      host: smtp.gmail.com
      user: d21gsd21gs@gmail.com
      password: ${EMAIL_PASSWORD}
      port: 587
  addresses:
    baseUrl: localhost:4200

server:
  servlet:
    context-path: /api