# Work in progress coming soon...
spring:
  data:
    mongodb:
      host: 10.245.0.16
      port: 27017
      database: desert21
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}

  authentication:
    cors:
      origins:
        - http://play.dev.desert21.com

  addresses:
    baseUrl: http://play.dev.desert21.com


