droidsConfig:
  cost: 5
  power: 21
  turnsToTrain: 1
  fieldsTraveledPerTurn: 2
  smallProduction: 10
  mediumProduction: 40
  massProduction: 100

tanksConfig:
  cost: 20
  power: 220
  turnsToTrain: 3
  fieldsTraveledPerTurn: 1
  smallProduction: 4
  mediumProduction: 11
  massProduction: 25

cannonsConfig:
  cost: 10
  power: 50
  turnsToTrain: 2
  fieldsTraveledPerTurn: 4
  smallProduction: 10
  mediumProduction: 30
  massProduction: 50

scarabsConfig:
  power: 10
  baseGeneration: 10
  additionalGenerationPerTurn: 2
  generationBias: 0.15

generalCombatConfig:
  destructionFunctionPolynomial:
    - 0.4
    - 0.6
    - 0.0
