combatBranchBalanceConfig:
  reusablePartsUnitsFractionSaved: 0.4

  improvedDroidsBaseDefenceBonus: 0.25
  improvedDroidsBaseAtTowerDefenceBonus: 0.4
  improvedTanksPowerBonus: 0.5

  improvedCannonsBombardingPowerFraction: 0.6

  advancedTacticsReferencePower: 100
  advancedTacticsPowerBonusPerReferencePower: 0.01

combatBranchCostConfig:
  reusableParts: 100

  mediumProduction: 200
  improvedDroids: 200
  improvedCannons: 400

  massProduction: 600
  improvedTanks: 600

  advancedTactics: 1400


controlBranchBalanceConfig:
  scarabScannersPowerDecreaseRatio: 0.5

  goldDiggersProductionPerFieldBonus: 2
  factoryTurretTowerLevel: 2

  towerCreatorMaxTowersBuilt: 2

controlBranchCostConfig:
  scarabScanners: 100

  kingOfDesert: 200
  theGreatFortress: 200
  towerCreator: 400

  goldDiggers: 600
  factoryTurret: 600

  superSonicRockets: 1400


productionBranchBalanceConfig:
  homeSweetHomeProductionBonus: 0.5

  moreMetalProductionRelativeBonus: 0.3
  moreBuildingMaterialsProductionRelativeBonus: 0.3
  moreElectricityProductionRelativeBonus: 0.3
  moreMetalProductionStaticBonus: 10
  moreBuildingMaterialsProductionStaticBonus: 10
  moreElectricityProductionStaticBonus: 10

  productionManagersProductionBonus: 0.2
  factoryBuildingMaxFactoriesBuilt: 4

  productionAiIncreasePerTurn: 40

productionBranchCostConfig:
  homeSweetHome: 100

  moreMetal: 200
  moreBuildingMaterials: 200
  moreElectricity: 200

  productionManagers: 600
  factoryBuilders: 800

  productionAi: 1400
