package com.github.maciejmalewicz.Desert21.config.gameBalance.lab;

public enum LabUpgrade {
    //COMBAT

    REUSABLE_PARTS,

    MEDIUM_PRODUCTION,
    IMPROVED_DROIDS,
    IMPROVED_TANKS,

    MASS_PRODUCTION,
    IMPROVED_CANNONS,

    ADVANCED_TACTICS,

    //CONTROL

    SCARAB_SCANNERS,

    KING_OF_DESERT,
    FACTORY_TURRET,
    GOLD_DIGGERS,

    TOWER_CREATOR,
    THE_GREAT_FORTRESS,

    SUPER_SONIC_ROCKETS,

    //PRODUCTION

    HOME_SWEET_HOME,

    MORE_METAL,
    MORE_BUILDING_MATERIALS,
    MORE_ELECTRICITY,

    PRODUCTION_MANAGERS,
    FACTORY_BUILDERS,

    PRODUCTION_AI;
}
