apiVersion: v1
kind: Service
metadata:
  name: backend-lb
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "backend-load-balancer"
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080