package com.github.maciejmalewicz.Desert21.config;

public class Constants {
    public static final String USER_ID_AUTH_PREFIX = "USER_";
    public static final String WEB_SOCKET_TOPICS_PATH = "/topics";
    public static final String WEB_SOCKET_USERS_PATH = "/users";

    public static final String NEXT_TURN_NOTIFICATION = "NEXT_TURN";
    public static final String START_GAME_NOTIFICATION = "START_GAME";
    public static final String RESOLUTION_PHASE_NOTIFICATION = "RESOLUTION_PHASE";

    public static final String BUILDING_UPGRADED_NOTIFICATION = "BUILDING_UPGRADED";
    public static final String RESOURCES_PRODUCED_NOTIFICATION = "RESOURCES_PRODUCED";
    public static final String UNOCCUPIED_FIELD_ENEMY_CONQUEST_FAILED_NOTIFICATION = "UNOCCUPIED_FIELD_ENEMY_CONQUEST_FAILED";
    public static final String UNOCCUPIED_FIELD_PLAYERS_CONQUEST_FAILED_NOTIFICATION = "UNOCCUPIED_FIELD_PLAYERS_CONQUEST_FAILED";
    public static final String UNOCCUPIED_FIELD_ENEMY_CONQUEST_SUCCEEDED_NOTIFICATION = "UNOCCUPIED_FIELD_ENEMY_CONQUEST_SUCCEEDED";
    public static final String UNOCCUPIED_FIELD_PLAYERS_CONQUEST_SUCCEEDED_NOTIFICATION = "UNOCCUPIED_FIELD_PLAYERS_CONQUEST_SUCCEEDED";
    public static final String ENEMY_CONQUEST_FAILED_NOTIFICATION = "ENEMY_CONQUEST_FAILED";
    public static final String PLAYERS_CONQUEST_FAILED_NOTIFICATION = "PLAYERS_CONQUEST_FAILED";
    public static final String ENEMY_CONQUEST_SUCCEEDED_NOTIFICATION = "ENEMY_CONQUEST_SUCCEEDED";
    public static final String PLAYERS_CONQUEST_SUCCEEDED_NOTIFICATION = "PLAYERS_CONQUEST_SUCCEEDED";
    public static final String LAB_UPGRADE_NOTIFICATION = "LAB_UPGRADE";
    public static final String ROCKET_STRIKE_NOTIFICATION = "ROCKET_STRIKE";
    public static final String ROCKET_STRIKE_DESTROYS_ROCKET_LAUNCHER_NOTIFICATION = "ROCKET_STRIKE_DESTROYS_ROCKET_LAUNCHER";
    public static final String BUILDING_BUILT_NOTIFICATION = "BUILDING_BUILT";

    public static final String UPGRADE_EVENT = "UPGRADE";
    public static final String TRAINING_EVENT = "TRAINING";
}
