package com.github.maciejmalewicz.Desert21.config;

public class Constants {
    public static final String USER_ID_AUTH_PREFIX = "USER_";
    public static final String WEB_SOCKET_TOPICS_PATH = "/topics";
    public static final String WEB_SOCKET_USERS_PATH = "/users";

    public static final String NEXT_TURN_NOTIFICATION = "NEXT_TURN";
    public static final String START_GAME_NOTIFICATION = "START_GAME";
    public static final String RESOLUTION_PHASE_NOTIFICATION = "RESOLUTION_PHASE";

    public static final String BUILDING_UPGRADED_NOTIFICATION = "BUILDING_UPGRADED";
    public static final String RESOURCES_PRODUCED_NOTIFICATION = "RESOURCES_PRODUCED";
    public static final String UNITS_TRAINED_NOTIFICATION = "UNITS_TRAINED";
    public static final String UNOCCUPIED_FIELD_ENEMY_CONQUEST_FAILED_NOTIFICATION = "UNOCCUPIED_FIELD_ENEMY_CONQUEST_FAILED";
    public static final String UNOCCUPIED_FIELD_PLAYERS_CONQUEST_FAILED_NOTIFICATION = "UNOCCUPIED_FIELD_PLAYERS_CONQUEST_FAILED";
    public static final String UNOCCUPIED_FIELD_ENEMY_CONQUEST_SUCCEEDED_NOTIFICATION = "UNOCCUPIED_FIELD_ENEMY_CONQUEST_SUCCEEDED";
    public static final String UNOCCUPIED_FIELD_PLAYERS_CONQUEST_SUCCEEDED_NOTIFICATION = "UNOCCUPIED_FIELD_PLAYERS_CONQUEST_SUCCEEDED";
    public static final String ENEMY_CONQUEST_FAILED_NOTIFICATION = "ENEMY_CONQUEST_FAILED";
    public static final String PLAYERS_CONQUEST_FAILED_NOTIFICATION = "PLAYERS_CONQUEST_FAILED";
    public static final String ENEMY_CONQUEST_SUCCEEDED_NOTIFICATION = "ENEMY_CONQUEST_SUCCEEDED";
    public static final String PLAYERS_CONQUEST_SUCCEEDED_NOTIFICATION = "PLAYERS_CONQUEST_SUCCEEDED";
    public static final String LAB_UPGRADE_NOTIFICATION = "LAB_UPGRADE";
    public static final String ROCKET_STRIKE_NOTIFICATION = "ROCKET_STRIKE";
    public static final String ROCKET_STRIKE_DESTROYS_ROCKET_LAUNCHER_NOTIFICATION = "ROCKET_STRIKE_DESTROYS_ROCKET_LAUNCHER";
    public static final String BUILDING_BUILT_NOTIFICATION = "BUILDING_BUILT";
    public static final String PLAYERS_BOMBARDING_SUCCEEDED_NOTIFICATION = "PLAYER_BOMBARDING_SUCCEEDED";
    public static final String ENEMY_BOMBARDING_SUCCEEDED_NOTIFICATION = "ENEMY_BOMBARDING_SUCCEEDED";
    public static final String PLAYERS_BOMBARDING_FAILED_NOTIFICATION = "PLAYER_BOMBARDING_FAILED";
    public static final String ENEMY_BOMBARDING_FAILED_NOTIFICATION = "ENEMY_BOMBARDING_FAILED";
    public static final String GAME_END_NOTIFICATION = "GAME_END";
    public static final String SURRENDER_NOTIFICATION = "SURRENDER";
    public static final String DRAW_REQUESTED_NOTIFICATION = "DRAW_REQUESTED";
    public static final String DRAW_REJECTED_NOTIFICATION = "DRAW_REJECTED";
    public static final String DRAW_ACCEPTED_NOTIFICATION = "DRAW_ACCEPTED";

    public static final String FRIENDS_INVITATION_RECEIVED_NOTIFICATION = "FRIENDS_INVITATION_RECEIVED";
    public static final String FRIENDS_LIST_UPDATED_NOTIFICATION = "FRIENDS_LIST_UPDATED";
    public static final String FRIENDS_INVITATION_ACCEPTED_NOTIFICATION = "FRIENDS_INVITATION_ACCEPTED";
    public static final String FRIENDS_INVITATION_REJECTED_NOTIFICATION = "FRIENDS_INVITATION_REJECTED";
    public static final String REMOVED_FROM_FRIEND_LIST_NOTIFICATION = "REMOVED_FROM_FRIEND_LIST";

    public static final String PING_REQUESTED_NOTIFICATION = "PING_REQUESTED";
    public static final String PLAYER_IN_GAME_NOTIFICATION = "PLAYER_IN_GAME";
    public static final String PLAYER_ACTIVE_NOTIFICATION = "PLAYER_ACTIVE";

    public static final String GAME_INVITATION_RECEIVED_NOTIFICATION = "GAME_INVITATION_RECEIVED";
    public static final String GAME_INVITATION_CANCELLED_NOTIFICATION = "GAME_INVITATION_CANCELLED";
    public static final String GAME_INVITATION_REJECTED_NOTIFICATION = "GAME_INVITATION_REJECTED";
    public static final String GAME_INVITATION_ACCEPTED_NOTIFICATION = "GAME_INVITATION_ACCEPTED";

    public static final String UPGRADE_EVENT = "UPGRADE";
    public static final String TRAINING_EVENT = "TRAINING";
    public static final String BUILD_EVENT = "BUILD";
}
