name: deploy
on:
  workflow_call:
    secrets:
      SECRET_KEY:
        required: true
      EMAIL_PASSWORD:
        required: true
      DATABASE_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: jar
          path: target/Desert21-0.0.0.jar
      - name: Create docker image
        run: docker image build -t docker-java-jar:latest .
      - name: Run docker image
        run: docker run docker-java-jar
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}