name: on-main-push
on: [pull_request]
#on:
#  push:
#    branches:
#      - main
jobs:
  verify_main:
    uses: ./.github/workflows/run-tests-workflow.yml
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

  build_main:
    needs: verify_main
    uses: ./.github/workflows/build-jar-workflow.yml
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

  create_image_main:
    needs: build_main
    uses: ./.github/workflows/create-image.yml
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}

  deploy_main:
    needs: create_image_main
    uses: ./.github/workflows/deploy.yml
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}