name: on-main-push
on:
  push:
    branches:
      - main
jobs:
  verify_main:
    uses: ./.github/workflows/run-tests.yml
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

  build_main:
    needs: verify_main
    uses: ./.github/workflows/build-jar.yml

  create_image_main:
    needs: build_main
    uses: ./.github/workflows/create-image.yml
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}

  deploy_main:
    needs: create_image_main
    uses: ./.github/workflows/deploy.yml
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_TOKEN: ${{ secrets.EMAIL_TOKEN }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}