name: on-pull-request
on: [pull_request]
#on:
#  push:
#    branches:
#      - main
jobs:
  verify:
    uses: ./.github/workflows/run-tests-workflow.yml@main
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}